### ISSUE TITLE
Unable to redirect nor pipe output

### ISSUE THREAD

**Issue by ogizanagi** [sensiolabs/melody#65] opened 2015-11-25 10:07 UTC
Hi !

Given this very simple witness script:
```php
<?php

<<<CONFIG
packages:
    - "php"
CONFIG;

echo 'Hello World'.PHP_EOL;
```

I'm unable to redirect the output to a file using standard or error output redirection:
```bash
$ melody run hello_world.php > hello.txt
# hello.txt remains empty
```

Here is the strace output captured by @lyrixx that might help, showing it seems to be properly output on FD1:
```Dtrace
16787 write(1, "/tmp/melody/aefded2aec05bb759178"..., 131) = 131
16787 write(1, "\n", 1)                 = 1
16787 lstat("/tmp/melody/aefded2aec05bb75917826c8787c3c6c24a4ff56cc67f6b6522fe8105cf4bc2c5/vendor/symfony/finder/Comparator/DateComparator.php", {st_mode=S_IFREG|0644, st_size=1465, ...}) = 0
16787 stat("/tmp/melody/aefded2aec05bb75917826c8787c3c6c24a4ff56cc67f6b6522fe8105cf4bc2c5/vendor/symfony/finder/Comparator/DateComparator.php", {st_mode=S_IFREG|0644, st_size=1465, ...}) = 0
16787 write(1, "/tmp/melody/aefded2aec05bb759178"..., 129) = 129
16787 write(1, "\n", 1)                 = 1
```

Any hint ? 

ping @smaftoul, if by chance you have any idea.

**Comment by smaftoul** [comment] 2015-11-25 11:03
Not sure I'll be able to help.
There might be some pty / forking stuff that breaks things somewhere, and this FD 1 might not be the same you have in your terminal. 
Can you provide a full strace (with `strace -s 65535 -f -o /tmp/strace.$$` ) ?
You might also have a look at `/proc/self/fd/1` within that process : is it a link ? where the link points to ? is the fd described answer true to `isatty()` ?

**Comment by lyrixx** [comment] 2015-11-25 11:07
Here is the (huge) log of strace ;)

I will look at it deeply later If I got some free time.

**Comment by smaftoul** [comment] 2015-11-25 12:20
@lyrixx where ?

**Comment by lyrixx** [comment] 2015-11-25 13:06
ahah, lol, forgot to paste the link:
https://gist.github.com/lyrixx/edcd46dd64d13e6737dd

**Comment by smaftoul** [comment] 2015-11-25 14:29
Not sure about it but we might lose the output here:
https://gist.github.com/lyrixx/edcd46dd64d13e6737dd#file-melody-fd-L2476-L2482

I'll try the real thing by running melody, but later ...

Anyway, you can check / follow calls to dup() / dup2() within all spawned process (we have 5 here, 27110 to 27114 ), and I suspect 27112 to be a double fork magic, that disconnects the actual terminal from the process.

**Comment by lyrixx** [comment] 2015-11-25 14:36
thanks @smaftoul  ;)

**Comment by lyrixx** [comment] 2015-11-26 14:05
I opened an issue [on symfony](https://github.com/symfony/symfony/issues/16683)

**Comment by romainneutron** [comment] 2015-12-07 09:42
Why do you use `setTty(true)`?

**Comment by jderusse** [comment] 2015-12-07 09:44
@romainneutron to handle the user input.

**Comment by lyrixx** [comment] 2015-12-07 09:44
For exemple, if the melody script use the console, and use `Question` helper.

**Comment by romainneutron** [comment] 2015-12-07 09:58
thanks @lyrixx

**Comment by romainneutron** [comment] 2015-12-07 10:18
Unfortunately, I don't think you can both inherit the TTY fds and get the output at the same time. I would close this issue as unfixable by design

**Comment by lyrixx** [comment] 2015-12-07 10:19
Ok. I'm closing this issue. 

If someone could solve this issue, please send a PR ;)

**Closed by lyrixx** 2015-12-07 10:19 UTC

**Comment by staabm** [comment] 2015-12-07 10:27
@romainneutron wouldnt it be possible to write the output of the running script into stdout, while writing all the questino related stuff into TTY?

**Comment by romainneutron** [comment] 2015-12-07 14:24
Might be very difficult. Would require to develop kind of a tee for pipes instead of plugging tty fds into proc_open.
